# docker-compose up -d
version: '3.8'

services:

  db:
    image: mysql
    container_name: vollmed_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vollmed
    ports:
      - 3306:3306